<x-mail::message>

# Hi {{ $userName }},

Order #{{ $orderId }} has been generated by Admin.

<x-mail::button :url="config('app.client_url') . '/service-team/orders/' . $orderId">
View Order
</x-mail::button>

Thanks,<br>
{{ config('app.name') }}
</x-mail::message>
