/*
 * Page routes list
 */
export const page_routes = {
  profile: { link: "/profile", name: "Profile" },
  login: { link: "/login", name: "Login" },
  forgot_password: { link: "/forgot-password", name: "Forgot Password" },
  reset_password: { link: "/reset-password", name: "Reset Password" },
  users: { link: "/users", name: "Users" },
  quotations: { link: "/quotations", name: "Quotations" },
  orders: { link: "/orders", name: "Orders" },
  activity_logs: { link: "/activity-logs", name: "Activity Logs" },
  public_quotations: { link: "/public/quotation", name: "Quotations" },
  sales_quotations: { link: "/sales/quotations", name: "Quotations" },
  sales_team_performance_report: { link: "/sales/reports/sales-performance", name: "Performance Report" },
  sales_team_lead_source_report: { link: "/sales/reports/sales-lead-source-performance", name: "Lead Source Report" },
  sales_team_approval_turn_around_report: { link: "/sales/reports/sales-approval-turn-around", name: "Approval Turn Around Report" },
  sales_team_trend_report: { link: "/sales/reports/sales-trend", name: "Trend Report" },
  sales_team_revenue_report: { link: "/sales/reports/sales-revenue", name: "Revenue Report" },
  sales_team_pipeline_status_report: { link: "/sales/reports/sales-pipeline-status", name: "Pipeline Status Report" },
  sales_team_profitability_per_quotation_report: { link: "/sales/reports/profitability-per-quotation", name: "Profit Per Quotation Report" },
  service_team_orders: { link: "/service-team/orders", name: "Orders" },
  approval_turn_around_reports: { link: "/reports/approval-turn-around", name: "Approval Turn Around Reports" },
  conversion_funnel_reports: { link: "/reports/conversion-funnel", name: "Conversion Funnel Reports" },
  profit_leaderboard_reports: { link: "/reports/profit-leaderboard", name: "Profit Leaderboard Reports" },
  sales_performance_reports: { link: "/reports/sales-performance", name: "Sales Performance Reports" },
  service_performance_reports: { link: "/reports/service-performance", name: "Service Performance Reports" },
  order_payment_reports: { link: "/reports/order-payment", name: "Order Payment Reports" },
  revenue_summary_reports: { link: "/reports/revenue-summary", name: "Revenue Summary Reports" },
  dashboard: { link: "/", name: "Dashboard" },
} as const;